message("--------------------------------------------------------------------")
message("   Summary of CMAKE environment variables")
message("--------------------------------------------------------------------")
message("BUILD TYPE: " ${CMAKE_BUILD_TYPE})
message( " ")
message("CMAKE_HOST_WIN32: " ${CMAKE_HOST_WIN32})
message("CMAKE_HOST_APPLE: " ${CMAKE_HOST_APPLE})
message( " ")
MESSAGE("Install to directory: " ${CMAKE_INSTALL_PREFIX})
message(" ")
message("Include directory: ")
message(" ==> ${INC_PATH}")
message("Library locations for external libraries:")
message(" ==> ${LIB_PATH}")

message(" ")
message("MAIN LIBRARIES:")
message("  GCC       ${LIB_GCC}")
message("  GDAL      ${LIB_GDAL}")
message(" ")
message("GDAL DEPENDENCIES:")
message("  LIBFREEXL      ${LIB_FREEXL}")
message("  LIBGIF         ${LIB_GIF}")
message("  LIBTIFF        ${LIB_TIFF}")
message("  LIBJPEG        ${LIB_JPEG}")
message("  LIBPNG         ${LIB_PNG}")
message("  LIBSPATIALITE  ${LIB_SPATIALITE}")
message("  LIBJSON_C      ${LIB_JSON_C}")
message("  LIB_EXPAT      ${LIB_EXPAT}")
message("  LIB_SQLITE3    ${LIB_SQLITE3}")
message("  LIB_XML2       ${LIB_XML2}")
message(" ")
message("RESULTING LIBRARY LINK DEFINITION")
message( "${EXTERNAL_LIBS}")

message(" ")
message("CMAKE_BINARY_DIR: " ${CMAKE_BINARY_DIR})
message("CMAKE_CURRENT_SOURCE_DIR: " ${CMAKE_CURRENT_SOURCE_DIR})
message("PROJECT_SOURCE_DIR: " ${PROJECT_SOURCE_DIR})
message( " ")
message("--------------------------------------------------------------------")
