message("--------------------------------------------------------------------")
message("   Summary of CMAKE environment variables")
message("--------------------------------------------------------------------")
message("BUILD TYPE: " ${CMAKE_BUILD_TYPE})
message( " ")
message("CMAKE_HOST_WIN32: " ${CMAKE_HOST_WIN32})
message("CMAKE_HOST_APPLE: " ${CMAKE_HOST_APPLE})
message( " ")
MESSAGE("Install to directory: " ${CMAKE_INSTALL_PREFIX})
message(" ")
message("Include directory: ")
message(" ==> ${INC_PATH}")
message("Library locations for external libraries:")
message(" ==> ${LIB_PATH}")

message(" ")
message("MAIN LIBRARIES:")
message("  GCC       ${LIB_GCC}")
message("  G++       ${LIB_GXX}")
message("  GDAL      ${LIB_GDAL}")
message(" ")
message("GDAL DEPENDENCIES:")
message("  LIB_FREEXL      ${LIB_FREEXL}")
message("  LIB_CURL        ${LIB_CURL}")
message("  LIB_DAP         ${LIB_DAP}")
message("  LIB_LDAP        ${LIB_LDAP}")
message("  LIB_SSL         ${LIB_SSL}")
message("  LIB_LWGEOM      ${LIB_LWGEOM}")
message("  LIB_PQ          ${LIB_PQ}")
message("  LIB_GEOS        ${LIB_GEOS}")
message("  LIB_GEOS_C      ${LIB_GEOS_C}")
message("  LIB_ICONV       ${LIB_ICONV}")
message("  LIB_Z           ${LIB_Z}")
message("  LIB_PCRE        ${LIB_PCRE}")
message("  LIB_GIF         ${LIB_GIF}")
message("  LIB_TIFF        ${LIB_TIFF}")
message("  LIB_GEOTIFF     ${LIB_GEOTIFF}")
message("  LIB_JPEG        ${LIB_JPEG}")
message("  LIB_PNG         ${LIB_PNG}")
message("  LIB_SPATIALITE  ${LIB_SPATIALITE}")
message("  LIB_JSON_C      ${LIB_JSON_C}")
message("  LIB_EXPAT       ${LIB_EXPAT}")
message("  LIB_SQLITE3     ${LIB_SQLITE3}")
message("  LIB_XML2        ${LIB_XML2}")
message(" ")
message("RESULTING LIBRARY LINK DEFINITION")
message( "${EXTERNAL_LIBS}")

message(" ")
message("CMAKE_BINARY_DIR: " ${CMAKE_BINARY_DIR})
message("CMAKE_CURRENT_SOURCE_DIR: " ${CMAKE_CURRENT_SOURCE_DIR})
message("PROJECT_SOURCE_DIR: " ${PROJECT_SOURCE_DIR})
message( " ")
message("--------------------------------------------------------------------")
